### ISSUE TITLE
Documentation, Rights n' Stuff

### ISSUE THREAD

**Issue by F1nx** [F1nx/pass#2]
For this project, since it is related to your work, @Russtopia, is there anything you would like to be done with the documentation & code related to giving you credit?

Like,
- _Copyright_
- _Credits_
- _Licensing_

This also includes any further documentation about your invention/concept itself.

**Comment by Russtopia** [comment]
? Just a link to the devices upon which it is based, eg. [the Tindie store](https://www.tindie.com/stores/Russtopia/) is fine.
